# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('mail', models.CharField(blank=True, max_length=30, null=True)),
                ('has_video', models.SmallIntegerField(default=0)),
                ('is_mobile_friendly', models.SmallIntegerField(default=0)),
                ('sent_count', models.SmallIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('datetime_of_last_change', models.DateTimeField(default=None)),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='LeadType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'lead_types',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=25)),
                ('body', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.LeadType'),
        ),
        migrations.AddField(
            model_name='lead',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Template'),
        ),
    ]
